version: 0.2

phases:
  install:
    versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing dependencies
      - npm -v
      - npm install
  build:
    commands:
      - npm run build